name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Módosítsd, ha másik branch-et használsz

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clone the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Módosíthatod, ha más verziót használsz

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build the project
      - name: Build the project
        run: npm run build

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
