version: "3.9"

services:
  backend:
    build: ./backend
    container_name: blog-backend
    environment:
      - VIRTUAL_HOST=api.rookiehu.me
      - VIRTUAL_PORT=8282
    env_file:
      - ./backend/.env
    ports:
      - "8282:8282"
    restart: unless-stopped
    networks:
      - nginx-proxy-network

  frontend:
    build: ./frontend
    container_name: blog-frontend
    environment:
      - VIRTUAL_HOST=rookiehu.me,www.rookiehu.me
      - VIRTUAL_PORT=80
    ports:
      - "5173:80"
    restart: unless-stopped
    networks:
      - nginx-proxy-network

networks:
  nginx-proxy-network:
    external: true
